# Natural Language Processing (NLP)

In [1]:
Var="Natural Language Processing (NLP) is a subfield of Artificial Intelligence (AI) that focuses on enabling computers to understand, interpret, and generate human language. While NLP is not synonymous with Machine Learning (ML), it heavily relies on ML techniques to achieve its goals."

In [2]:
Var

'Natural Language Processing (NLP) is a subfield of Artificial Intelligence (AI) that focuses on enabling computers to understand, interpret, and generate human language. While NLP is not synonymous with Machine Learning (ML), it heavily relies on ML techniques to achieve its goals.'

In [3]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\wpram\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\wpram\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\wpram\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\wpram\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\wpram\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\wpram\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\wpram\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\wpram\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\wpram\anaconda3\Lib\site-packages)

In [4]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [5]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\wpram\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\wpram\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [6]:
sent=sent_tokenize(Var)

In [7]:
sent

['Natural Language Processing (NLP) is a subfield of Artificial Intelligence (AI) that focuses on enabling computers to understand, interpret, and generate human language.',
 'While NLP is not synonymous with Machine Learning (ML), it heavily relies on ML techniques to achieve its goals.']

In [8]:
Var_new=word_tokenize(Var)

In [9]:
Var_new

['Natural',
 'Language',
 'Processing',
 '(',
 'NLP',
 ')',
 'is',
 'a',
 'subfield',
 'of',
 'Artificial',
 'Intelligence',
 '(',
 'AI',
 ')',
 'that',
 'focuses',
 'on',
 'enabling',
 'computers',
 'to',
 'understand',
 ',',
 'interpret',
 ',',
 'and',
 'generate',
 'human',
 'language',
 '.',
 'While',
 'NLP',
 'is',
 'not',
 'synonymous',
 'with',
 'Machine',
 'Learning',
 '(',
 'ML',
 ')',
 ',',
 'it',
 'heavily',
 'relies',
 'on',
 'ML',
 'techniques',
 'to',
 'achieve',
 'its',
 'goals',
 '.']

In [10]:
from nltk.corpus import stopwords

In [11]:
import nltk

nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\wpram\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [12]:
stop=stopwords.words("english")

In [13]:
stop

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [14]:
from string import punctuation

In [15]:
stop1=list(punctuation)

In [16]:
stop1

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [17]:
remove=stop+stop1

In [18]:
remove

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've",
 '!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [19]:
for i in Var_new:
    if i not in remove:
        print(i)

Natural
Language
Processing
NLP
subfield
Artificial
Intelligence
AI
focuses
enabling
computers
understand
interpret
generate
human
language
While
NLP
synonymous
Machine
Learning
ML
heavily
relies
ML
techniques
achieve
goals

In [20]:
from nltk.stem import  LancasterStemmer,RegexpStemmer,PorterStemmer,SnowballStemmer

In [21]:
l=LancasterStemmer()
r=RegexpStemmer("ing")
p=PorterStemmer()
s=SnowballStemmer("english")

In [22]:
l.stem("Changed")

'chang'

In [23]:
l.stem("Changing")

'chang'

In [24]:
r.stem("Changing")

'Chang'

In [25]:
r.stem("Changed")

'Changed'

In [26]:
p.stem("studying")

'studi'

In [27]:
p.stem("Playing")

'play'

In [28]:
s.stem("Changed")

'chang'

In [29]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\wpram\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [30]:
from nltk.stem import WordNetLemmatizer

In [31]:
wl=WordNetLemmatizer()

In [32]:
wl.lemmatize("mice")

'mouse'

In [33]:
wl.lemmatize("changing",pos='v')

'change'

### N-gram

In [ ]:
An N-gram in Natural Language Processing (NLP) is a contiguous sequence of $N$ items (words, characters, or symbols) 
extracted from a given text or speech corpus.N-grams are fundamental statistical tools used to analyze language patterns, 
predict words, and process textual data.
Common N-gram TypesThe value of $N$ determines the size of the window used to group text:
    1) Unigram ($N=1$): Single words processed independently.
    Example: "Data", "science", "is", "fun"
    2)Bigram ($N=2$): Pairs of consecutive words.
    Example: "Data science", "science is", "is fun"
    3)Trigram ($N=3$): Triplets of consecutive words.
    Example: "Data science is", "science is fun"
    4-gram / $N$-gram ($N \ge 4$): Sequences of $N$ words.
    Example (4-gram): "Data science is fun"

In [38]:
x="i am student i am studying i am learning studying a ML ML is agood subject"

In [39]:
x

'i am student i am studying i am learning studying a ML ML is agood subject'

In [40]:
from nltk.tokenize import word_tokenize

In [41]:
w=word_tokenize(x)

In [42]:
w

['i',
 'am',
 'student',
 'i',
 'am',
 'studying',
 'i',
 'am',
 'learning',
 'studying',
 'a',
 'ML',
 'ML',
 'is',
 'agood',
 'subject']

In [43]:
from nltk.collocations import BigramCollocationFinder,TrigramCollocationFinder,ngrams

In [44]:
b=BigramCollocationFinder.from_words(w)

In [45]:
b.ngram_fd

FreqDist({('i', 'am'): 3, ('am', 'student'): 1, ('student', 'i'): 1, ('am', 'studying'): 1, ('studying', 'i'): 1, ('am', 'learning'): 1, ('learning', 'studying'): 1, ('studying', 'a'): 1, ('a', 'ML'): 1, ('ML', 'ML'): 1, ...})

In [46]:
t=TrigramCollocationFinder.from_words(w)

In [47]:
t.ngram_fd

FreqDist({('i', 'am', 'student'): 1, ('am', 'student', 'i'): 1, ('student', 'i', 'am'): 1, ('i', 'am', 'studying'): 1, ('am', 'studying', 'i'): 1, ('studying', 'i', 'am'): 1, ('i', 'am', 'learning'): 1, ('am', 'learning', 'studying'): 1, ('learning', 'studying', 'a'): 1, ('studying', 'a', 'ML'): 1, ...})

In [48]:
n=ngrams(w,2)

In [49]:
for i in n:
    print(i)

('i', 'am')
('am', 'student')
('student', 'i')
('i', 'am')
('am', 'studying')
('studying', 'i')
('i', 'am')
('am', 'learning')
('learning', 'studying')
('studying', 'a')
('a', 'ML')
('ML', 'ML')
('ML', 'is')
('is', 'agood')
('agood', 'subject')

# NLP PROJECT 🚀💻

In [64]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [65]:
df = pd.read_csv(r'C:\Users\wpram\Downloads\train.txt\train.txt', sep=';', names=['text', 'emotions'])

In [3]:
df

                                                    text emotions
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [4]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [5]:
df['emotions'].unique()

<ArrowStringArray>
['sadness', 'anger', 'love', 'surprise', 'fear', 'joy']
Length: 6, dtype: str

In [6]:
ord_data={'sadness':0, 'anger':1, 'love':2, 'surprise':3, 'fear':4, 'joy':5}

In [7]:
df['emotions']=df['emotions'].map(ord_data)

In [8]:
df.head(10)

                                                text  emotions
0                            i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...         0
2   im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...         2
4                               i am feeling grouchy         1
5  ive been feeling a little burdened lately wasn...         0
6  ive been taking or milligrams or times recomme...         3
7  i feel as confused about life as a teenager or...         4
8  i have been with petronas for years i feel tha...         5
9                                i feel romantic too         2

In [9]:
df['text'] = df['text'].apply(lambda x:x.lower())

In [10]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [11]:
import string

def remove_punc(txt):
    if isinstance(txt, str):
        return txt.translate(str.maketrans("", "", string.punctuation))

In [12]:
df['text']=df['text'].apply(remove_punc)

In [13]:
df.head(5)

                                                text  emotions
0                            i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...         0
2   im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...         2
4                               i am feeling grouchy         1

In [14]:
import re

def remove_number(txt):
  return re.sub(r"\d+", "", str(txt))

df["text"] = df["text"].apply(remove_number)

In [15]:
df['text']=df['text'].apply(remove_number)

In [16]:
df.head(5)

                                                text  emotions
0                            i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...         0
2   im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...         2
4                               i am feeling grouchy         1

In [17]:
def remove_emoji(txt):
  return "".join([i for i in str(txt) if i.isascii()])

In [18]:
df['text']=df['text'].apply(remove_emoji)

In [19]:
df.head(5)

                                                text  emotions
0                            i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...         0
2   im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...         2
4                               i am feeling grouchy         1

In [20]:
import nltk

In [21]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\wpram\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [22]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [23]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\wpram\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [24]:
stop_word=set(stopwords.words('english'))

In [25]:
stop_word

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [26]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [27]:
def remove(txt):
    word = word_tokenize(txt)
    cleaned = []
    for i in word:
        if i not in stop_word:
            cleaned.append(i)
    return ' '.join(cleaned)

In [28]:
df['text']=df['text'].apply(remove)

In [29]:
df

                                                    text  emotions
0                                  didnt feel humiliated         0
1      go feeling hopeless damned hopeful around some...         0
2              im grabbing minute post feel greedy wrong         1
3      ever feeling nostalgic fireplace know still pr...         2
4                                        feeling grouchy         1
...                                                  ...       ...
15995      brief time beanbag said anna feel like beaten         0
15996  turning feel pathetic still waiting tables sub...         0
15997                           feel strong good overall         5
15998                     feel like rude comment im glad         1
15999                       know lot feel stupid portray         0

[16000 rows x 2 columns]

In [30]:
x=df['text']
y=df['emotions']

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [33]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [34]:
from sklearn.feature_extraction.text import CountVectorizer

cv=cv=CountVectorizer()

x_train_bg=cv.fit_transform(x_train)

x_test_bg=cv.transform(x_test)

In [35]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_bg,y_train)

MultinomialNB()

In [36]:
pred=model.predict(x_test_bg)

In [37]:
pred

array([0, 5, 0, ..., 5, 5, 0], shape=(3200,))

In [38]:
model.score(x_test_bg,y_test)*100

76.78125

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf=TfidfVectorizer()

x_train_tf = tf.fit_transform(x_train)

x_test_tf = tf.transform(x_test)

In [40]:
model.fit(x_train_bg,y_train)

MultinomialNB()

In [41]:
pred=model.predict(x_test_tf)

In [42]:
pred

array([0, 5, 0, ..., 5, 5, 0], shape=(3200,))

In [43]:
model.score(x_test_tf,y_test)*100

72.75

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
lr= LogisticRegression()

In [46]:
lr.fit(x_train_bg,y_train)

LogisticRegression()

In [47]:
lr.score(x_test_bg,y_test)*100

88.875

In [48]:
lr.fit(x_train_tf,y_train)

LogisticRegression()

In [49]:
lr.score(x_test_tf,y_test)*100

86.15625

In [50]:
reverse_map={
    0:'sadness', 
    1:'anger', 
    2:'love', 
    3:'surprise', 
    4:'fear',
    5:'joy'
}

In [58]:
def predict_emotions(text):
    text=text.lower()

    #remove_punctuation
    text= remove_punc(text)
    text= remove_number(text)

    #remove_emoji
    text=remove_emoji(text)
    
    #remove stopword
    text=remove(text)

    #convert text into vector
    text_vector=cv.transform([text])

    #predict
    pred=int(model.predict(text_vector)[0])

    #convert number bact to emotions
    return reverse_map[pred]

In [59]:
new_text= "i am feeling 5 very happy 😊 today!"

In [60]:
result=predict_emotions(new_text)

In [61]:
result

'joy'

In [62]:
print(predict_emotions("i not get holiday so i feel terrible"))

sadness

In [63]:
print(predict_emotions("someone is following me 😒and i am scared!"))

fear